
name: Terraform Apply

on:
  push:
    branches:
      - main   # Run when code is pushed to the 'main' branch
  pull_request:
    branches:
      - main   # Run for pull requests targeting 'main'

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: '1.5.0'  # Specify the desired Terraform version

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}

    - name: Initialize Terraform
      run: terraform init

    - name: Plan Terraform deployment
      run: terraform plan

    - name: Apply Terraform deployment
      run: terraform apply -auto-approve