
name: Terraform Apply

on:
  push:
    branches:
      - main   # Run when code is pushed to the 'main' branch
      
jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: '1.5.0'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}  # Define the region directly

    - name: Initialize Terraform
      run: terraform init

    - name: Plan Terraform deployment
      run: terraform plan

    - name: Apply Terraform deployment
      run: terraform apply -auto-approve